name: Update Bang List (Pull Request)

on:
  schedule:
    # Run on the 1st of every month at 2 AM UTC
    - cron: '0 2 1 * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-bangs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Use personal access token for protected branches
          token: ${{ secrets.PAT_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Validate current bang list
        run: npm run validate-bangs
        
      - name: Update bang list
        run: node scripts-for-workflow/update-ddg-bangs.js
        
      - name: Validate updated bang list
        run: npm run validate-bangs
        
      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Number of changes:"
            git status --porcelain | wc -l
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          fi
          
      - name: Create Pull Request
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Create a new branch
          BRANCH_NAME="update-bangs-$(date +%Y%m%d-%H%M%S)"
          git checkout -b "$BRANCH_NAME"
          
          # Add and commit changes
          git add src/bang.ts
          git commit -m "chore: update bang list from DuckDuckGo API"
          
          # Push the branch
          git push --set-upstream origin "$BRANCH_NAME"
          
          # Create pull request using GitHub CLI
          gh pr create \
            --title "🔄 Update DuckDuckGo Bang List" \
            --body "This PR updates the DuckDuckGo bang list with the latest entries from their API. Generated on: $(date -u +"%Y-%m-%d %H:%M UTC"). Please review and merge if everything looks good." \
            --base main \
            --head "$BRANCH_NAME"
          
      - name: Build verification
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          npm run build
          echo "✅ Build verification passed"
          
      - name: Summary
        run: |
          echo "=== Workflow Summary ==="
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Changes detected: ${{ steps.verify-changed-files.outputs.changed }}"
          if [ "${{ steps.verify-changed-files.outputs.changed }}" == "true" ]; then
            echo "✅ Bang list updated successfully"
            echo "📝 Pull request created for review"
            echo "🔍 Check the Actions tab for the PR link"
          else
            echo "ℹ️ No updates needed"
          fi
