name: Update Bang List

on:
  schedule:
    # Run on the 1st of every month at 2 AM UTC
    - cron: '0 2 1 * *'
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [main, master]
    paths: ['.github/workflows/update-ddg-bangs.yml'] # Run when this workflow is updated

jobs:
  update-bangs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Validate current bang list
        run: npm run validate-bangs
        
      - name: Update bang list
        run: node scripts-for-workflow/update-ddg-bangs.js
        
      - name: Validate updated bang list
        run: npm run validate-bangs
        
      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Number of changes:"
            git status --porcelain | wc -l
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          fi
          
      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/bang.ts
          git commit -m "chore: update bang list from DuckDuckGo API [skip ci]"
          git push
          
      - name: Build and deploy
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          npm run build
          echo "Bang list updated and built successfully!"
          
      - name: Summary
        run: |
          echo "=== Workflow Summary ==="
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Changes detected: ${{ steps.verify-changed-files.outputs.changed }}"
          if [ "${{ steps.verify-changed-files.outputs.changed }}" == "true" ]; then
            echo "✅ Bang list updated successfully"
          else
            echo "ℹ️ No updates needed"
          fi 
